apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: warproject1
  name: warproject1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warproject1
  template:
    metadata:
      labels:
        app: warproject1
    spec:
      containers:
        - image: quay.io/rohanp/warproject:dev1
          imagePullPolicy: Always
          name: warproject1
          ports:
            - containerPort: 8080
              protocol: TCP

