apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:db5612806274124970649cb37c1a890a70e57890a4de518a588d79a6cec41cc3
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:a95d7fa0d54a5c39df07f164b1488db04930f057
