apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:0e91da920f5ae223c0cc66e9709fd1423024a3de072faacf14f1d568897089c3
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:test1
