apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:ce418d4ececec4f7b829933f3c5533d676fa988db40da01e1a3f968a39e16a46
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:e7ae2e98958f8f284aab1b9339da26e9e9ab44e0
