apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:aea27ded9a9259d684e299fa505e7565ba11d00a8602ee778d0334de99e2a523
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:424a1dbfcc5677908c3186b4507238baa2a1ecc8
