apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:133f56c231f4e1f4238459dfdc22b605e42714f3857c69d759b457d9a6949d25
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:a95d7fa0d54a5c39df07f164b1488db04930f057
