apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:314c0e7119861a065ddeeebfd6b566c91feebf660e4e9b3cf4ce3487efe6d5d8
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:e7ae2e98958f8f284aab1b9339da26e9e9ab44e0
