apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:eb32694688ebee2d8bd1afe6ee6890f917abe762d5cae6ab34ad474e73316756
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:80d1babde97ee44b36507735dbd876a97d0245c7
