apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:b89e74b34f4b77660417fa2b044c087039bfd38f411e267b6010bfc2d0ffe3b0
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:test1
- digest: sha256:3bc59e00318e675842794ef1e5bfa5370b95aefd2e98221cbe5351f0dc393532
  name: quay.io/rohanp/warproject1
  newName: quay.io/rohanp/warproject1:test1
