apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:1f329ffd6f0346cade9696717a2024552c46061045e4cdfae4a749175f97f764
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:efc4c8185ddb07d96a4caacdf109b68ebc8746fd
