apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
- new-deployment.yaml
- new-route.yaml
- new-service.yaml
images:
- digest: sha256:2f23cc55ff9721adf7f92b880ccb140859317f978c3e03eea03b0f9a9fe6ba76
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:1abad919fe27f54eff825547ff086bc74a7a1b0d
