apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:8aa18c74fda4471c49f430d8cf1209da16710d79631bd459c031b59520880f29
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:b4c9bb0eb7b01c90f3bd3db757c91ced991594ee
