apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:118582dbc5543f395935109bd182e2d767cbcbceba26d64cf8b99d02e5d95081
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:e18dd11804eef3611822781ef828c62379f3115e
