apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:6895acef8d5ec8532a3bf87b8fa287c6724a775859e63b0e78b4064f92180d6b
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:test
