apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:709702a50dee2779d806581034feda9ca9086f508fb45c32ff3cbafe148a648a
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:test
