apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
# - new-deployment.yaml
# - new-route.yaml
# - new-service.yaml
images:
- digest: sha256:0fc89eb66d26b17ef9c3e32e5a92134a0fa56d7af1eb52b48163ca6dd6bffc80
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:1abad919fe27f54eff825547ff086bc74a7a1b0d
