apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:f21f3556a025260621a5b2fd218e876a7fd3df83bc7594d90b407e3621e91b30
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:e18dd11804eef3611822781ef828c62379f3115e
