apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:eb960429a51548226c1a3d013695fedb92c31468ad7f03f97b2ac2a1e31ac979
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:test
