apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:31eb08189408d81731b22ac0dd00ea3b68d7581b38ebc1042b14f2c697408618
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:test
