apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:26a32f1e6345c34eb84ff4dc5cd5d87db56480b4d81f8b31f330796cd5f9a5c7
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:424a1dbfcc5677908c3186b4507238baa2a1ecc8
