apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:7e1e9e8b557681b9dff21d12b3dbba7853a62f6d293040308185c2f7087caec9
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:test
