apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:9d7e6cb56f3b2e8980aff4ce51fed801db98a60f8ffb8294023b0e83939d0e88
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:37058903529cc556097a4c9d69df167a2d17488e
