apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:1e2fa5f9f0a297409a3d41b9fff9ee4a2bd911c347cf06fcfc61ccb924e32c81
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:test
