apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:a9bdf30cf36e3dc63b4bbddbb7a050dee1efce3b35e871703ae2b8e54d32eed9
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:606e94b0a8a5f0814661f22e2ffe6d012be4cf95
