apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:3e3ae416530ecf37c638a0d6cdb590c0b5bc06d14517aa206e8950578fdd005e
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:80d1babde97ee44b36507735dbd876a97d0245c7
