apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:9bc3a16fcf4397efd0ef1deba37fc8855a62f7059b2de4b55ded91a2bc1bd8ff
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:a95d7fa0d54a5c39df07f164b1488db04930f057
