apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:1e60ac10bb67bae512a234e5fa46deebed7a098e1e8e7a40fb567c850f22f718
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:80d1babde97ee44b36507735dbd876a97d0245c7
