apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:f7b63c04d7666c7e8429089def9b7a6775ae3b06bc12d8221c559e5a194b8c33
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:e18dd11804eef3611822781ef828c62379f3115e
