apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:5d16a12f0018ccc26226003db617a7863721167e3821fb835a486bf23f2e7f30
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:0d5e7b1efe47f8a0db4b2db0d9b44c51c952ce5e
