apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:08f500dd34ed06b2a3059a85aea375b46430e32fda4a719c95615f393e98341c
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:979697642ed519146868bcdc80a85a3673e70584
