apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:21a069ceab8e9d5aa1678ac8291ee3af63daf16746544568669a7df4a5433f66
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:test
