apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:f4359775e787078909f9813dfc5e52dd2656ec4375f49e0cf02f239d6e77d32a
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:73edb3c223879a9e54e137a6fb2246cbe0ba2a96
