apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:f33796346a0ef0d1ba748afecc917546eac4492c3f643f23e5595213bce92959
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:606e94b0a8a5f0814661f22e2ffe6d012be4cf95
