apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:edab56895e73f39956a06043ec72b383ec2be67d4148dc3475172fd9fd5c2b48
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:e18dd11804eef3611822781ef828c62379f3115e
