apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:7ba3cb99274fc9969a21b245af55f63915341221de66eabcb4d504a080bb7ce9
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:test
