apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:b73b20c637ed31faca4c6adf7978f003367396f990ad64d3ccf9c09a48ae9777
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:e7ae2e98958f8f284aab1b9339da26e9e9ab44e0
