apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:1ea3cbbe053d817e3572904f605060147c08aa4372dfcff613ecf969c0a104ca
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:a95d7fa0d54a5c39df07f164b1488db04930f057
