apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:4d2535fd62e9d48e97baa1641cd250736007a1de8c3e36f858259a32eabd8e3f
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:a95d7fa0d54a5c39df07f164b1488db04930f057
