apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:0435e60994170651fba377bfc6de746565245df9d35bea3bbcde3f7b177dd8d2
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:e7ae2e98958f8f284aab1b9339da26e9e9ab44e0
