apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
- new-deployment.yaml
- new-route.yaml
- new-service.yaml
images:
- digest: sha256:b89e74b34f4b77660417fa2b044c087039bfd38f411e267b6010bfc2d0ffe3b0
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:7fdfce14ba2b0195f512099343364f6dd60fd599
- digest: sha256:3225da2ce11e63b3a8045b43b62684c1469fcec057401a0a99b1d59faf24ef2d
  name: quay.io/rohanp/warproject1
  newName: quay.io/rohanp/warproject1:1abad919fe27f54eff825547ff086bc74a7a1b0d
