apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:7f5a3dea16ca4c817d6a4ab1e708673612933a09551fec7244dcfb90dc9f3bfa
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:test
