apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:7f711a99b64e637b2a5a7c9a6da0e8c8a187933fe17055c869b89f51f3f400a5
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:test
