apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:a31004e6ba1bc7a576a48b626e9be239437cfb524aa9edcd0f170eafdec76e4a
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:test
