apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:678749115fbb087613c2ec31c88c860d960532f42cdc87827bfca0f94c37100f
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:test1
- digest: sha256:3225da2ce11e63b3a8045b43b62684c1469fcec057401a0a99b1d59faf24ef2d
  name: quay.io/rohanp/warproject1
  newName: quay.io/rohanp/warproject1:test1
