apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:9df350092fe4a15da0e12c8804a529e4cc3f0f99e0c9c63c67e34f934621a121
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:424a1dbfcc5677908c3186b4507238baa2a1ecc8
