apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:4cd20808e047322bf2659ba13ef017fb83afc6e124250a948975b130d7cbc69e
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:606e94b0a8a5f0814661f22e2ffe6d012be4cf95
