apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: sonarqube
  name: sonarqube
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: sonarqube
    weight: 100
