apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: warproject
  name: warproject
spec:
  port:
    targetPort: "tcp-8080"
  to:
    kind: Service
    name: warproject
    weight: 100
  path: /WebApp
