apiVersion: v1
kind: Service
metadata:
  labels:
    app: warproject
  name: warproject
spec:
  type: ClusterIP
  ports:
    - name: "tcp-8080"
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: warproject
