apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:cc11309ed4d4cd7f6c7559646188f8c1b45322a9717454a777a3c1f3a6160809
  name: quay.io/rohanp/newdemo:latest
  newName: quay.io/rohanp/newdemo
