apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:4f6697fe6493737956a747c1b62282383a515a94558277eff0c1457b34b92a2e
  name: quay.io/rohanp/newdemo:latest
  newName: quay.io/rohanp/newdemo
