apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:8d7a9a1798e515628f35aeab733eea401d3789454c27821cb5d9e91b5c954b0c
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject
