apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:8eb930b4889279ec3e6b15eec4121071ff900dee6ccd2a0dc981e60898064a88
  name: quay.io/rohanp/newdemo:latest
  newName: quay.io/rohanp/newdemo
